2025-10-20 03:31:10,406 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:31:35,348 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:31:40,925 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:31:46,506 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:31:52,082 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:31:57,638 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:01,778 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:08,121 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:13,705 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:19,272 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:24,847 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:30,391 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:35,923 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:41,496 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:47,050 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:52,628 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:38:58,204 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:39:03,762 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:39:09,307 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:39:14,886 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:39:20,447 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:39:26,024 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
2025-10-20 03:39:31,587 [ERROR] Listener error: timed out
Traceback (most recent call last):
  File "d:\0)Projects\fatomaa\Live-Quiz-Server\client.py", line 41, in listener
    data, _ = sock.recvfrom(4096)
              ~~~~~~~~~~~~~^^^^^^
TimeoutError: timed out
